public class Utils {

    public static byte[] shortArrayToByteArray(short[] shorts) {  // generated by ChatGPT
        byte[] bytes = new byte[shorts.length * 2]; // Each short = 2 bytes
        for (int i = 0; i < shorts.length; i++) {
            bytes[i * 2] = (byte) (shorts[i] >> 8);  // High byte
            bytes[i * 2 + 1] = (byte) (shorts[i]);   // Low byte
        }
        return bytes;
    }

    public static byte[] concatByteArrays(byte[] first, byte[] second) {
        // Create a new array to hold both byte arrays
        byte[] concatenatedArray = new byte[first.length + second.length];
        // Copy the first array into the new array
        System.arraycopy(first, 0, concatenatedArray, 0, first.length);
        // Copy the second array into the new array
        System.arraycopy(second, 0, concatenatedArray, first.length, second.length);
        // Print concatenated array
        return concatenatedArray;
    }
}
